
name: covid19sf data refresh

on: 
  schedule:
    - cron:  '30 */4 * * *'
jobs:
  data_refresh_master:
    name: covid19sf dataset refresh dev
    runs-on: ubuntu-18.04 
    container: 
     image:  rkrispin/covid19sf:dev
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'master'
      - name: Refresh the data
        run: bash ./data_raw/data_refresh.sh
